theme: jekyll-theme-midnight

name: 3NodeDev
description: ..a blog coming to you soon... from a highly disturbed, arrogant and opinionated Systems Administrator, Hardware Tech, Developer.
He's had enough and is mad tired as HELL! 

author: 3NodeDev

